イベント開催会場を株式会社インプレスに更新
porisuka/ichiyasaGitSample pull request #1
Opened 2024-08-25 05:50 UTC by porisuka

### 変更内容
 イベント開催会場を「株式会社インプレス」に更新しました。

### 背景
 「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2024-08-25 09:34 UTC, inamiasuka commented
修正ありがとうございます。問題ないのでマージします。

2024-08-25 10:06 UTC, inamiasuka requested changes
修正ありがとうございます！指摘の確認と修正をお願いします。

2024-08-25 10:06 UTC, inamiasuka commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
レビューの練習

2024-08-25 10:24 UTC, porisuka commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
レビュイーの立場から練習

2024-08-26 14:40 UTC, inamiasuka commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
LGTM

2024-08-26 14:43 UTC, porisuka commented
修正しました

2024-08-26 14:47 UTC, inamiasuka approved these changes

2024-08-26 14:51 UTC, merged